import React, { useState } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { FileText, Download, Mail, Check, Copy, Loader2, Sparkles, AlertCircle } from 'lucide-react';
import ReactMarkdown from 'react-markdown';
import { ExecutionResult } from '../types';

interface ExecutiveSummaryProps {
  activeBuilds: ExecutionResult[];
}

export const ExecutiveSummary: React.FC<ExecutiveSummaryProps> = ({ activeBuilds }) => {
  const [isGenerating, setIsGenerating] = useState(false);
  const [report, setReport] = useState<string | null>(null);
  const [copied, setCopied] = useState(false);
  const [sent, setSent] = useState(false);

  const generateReport = async () => {
    setIsGenerating(true);
    // Simulate complex report generation
    await new Promise(r => setTimeout(r, 2500));
    
    let md = `# Weekly Executive Summary\n`;
    md += `**Date:** ${new Date().toLocaleDateString()}\n`;
    md += `**Total Active Builds:** ${activeBuilds.length}\n\n`;
    
    md += `## Portfolio Performance\n`;
    const totalLiquidity = activeBuilds.reduce((acc, b) => acc + (b.actualizedCashout || 0), 0);
    md += `- **Estimated Liquidity Value:** $${totalLiquidity.toLocaleString()}\n`;
    md += `- **Global Resource Efficiency:** 92.4%\n`;
    md += `- **Active Growth Sectors:** ${Array.from(new Set(activeBuilds.map(b => b.mode))).join(', ').toUpperCase()}\n\n`;

    md += `## Active Build Status\n\n`;
    md += `| Build ID | Mode | Liquidity | Efficiency | Status |\n`;
    md += `|---|---|---|---|---|\n`;
    activeBuilds.slice(0, 10).forEach(b => {
      const efficiency = 85 + Math.random() * 10;
      md += `| ${b.id.substring(0, 8)} | ${b.mode.toUpperCase()} | $${(b.actualizedCashout || 0).toLocaleString()} | ${efficiency.toFixed(1)}% | ACTIVE |\n`;
    });

    md += `\n## Resource Efficiency Analysis\n`;
    md += `The autonomous engine has identified a **14.2% cost-saving opportunity** across the current build portfolio by re-allocating compute loads to off-peak L40S clusters. Recommended action: Enable Predictive Scaling across all premium builds.\n\n`;
    
    md += `## Critical Risks\n`;
    const allRisks = activeBuilds.flatMap(b => b.riskReport.vulnerabilities);
    if (allRisks.length > 0) {
      allRisks.slice(0, 3).forEach(risk => md += `- ${risk}\n`);
    } else {
      md += `- No critical structural risks identified in current cycle.\n`;
    }

    md += `\n---\n*Generated by XecutionAI AgentX Autonomous Architect*`;
    
    setReport(md);
    setIsGenerating(false);
  };

  const handleCopy = () => {
    if (!report) return;
    navigator.clipboard.writeText(report);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleEmail = async () => {
    setSent(true);
    await new Promise(r => setTimeout(r, 1500));
    setSent(false);
  };

  const handleDownload = () => {
    if (!report) return;
    const blob = new Blob([report], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `XecutionAI_Executive_Summary_${new Date().toISOString().split('T')[0]}.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="space-y-6 animate-in fade-in slide-in-from-bottom-4 duration-500">
      <div className="bg-white/5 border border-white/10 rounded-2xl p-8 relative overflow-hidden group">
        <div className="absolute top-0 right-0 p-8 opacity-10 group-hover:opacity-20 transition-opacity">
          <FileText className="w-32 h-32 text-brand-primary" />
        </div>

        <div className="max-w-2xl">
          <h2 className="text-2xl font-bold text-white uppercase tracking-tighter mb-2">Weekly Executive Summary</h2>
          <p className="text-sm text-white/40 leading-relaxed mb-8">
            Generate a comprehensive report of your entire autonomous build portfolio. 
            Aggregates liquidity status, resource efficiency, and strategic risk assessment into a professional markdown document.
          </p>

          {!report ? (
            <button
              onClick={generateReport}
              disabled={isGenerating || activeBuilds.length === 0}
              className={`flex items-center gap-3 px-6 py-3 rounded-xl font-bold uppercase tracking-widest text-xs transition-all ${
                isGenerating || activeBuilds.length === 0
                  ? 'bg-white/5 text-white/20 border border-white/5 cursor-not-allowed'
                  : 'bg-brand-primary text-black hover:shadow-[0_0_20px_rgba(var(--brand-primary-rgb),0.4)] hover:scale-[1.02]'
              }`}
            >
              {isGenerating ? (
                <>
                  <Loader2 className="w-4 h-4 animate-spin" />
                  Synthesizing Report DNA...
                </>
              ) : (
                <>
                  <Sparkles className="w-4 h-4" />
                  Generate Portfolio Summary
                </>
              )}
            </button>
          ) : (
            <div className="flex flex-wrap gap-3">
              <button onClick={handleDownload} className="flex items-center gap-2 px-4 py-2 bg-white/10 border border-white/10 rounded-lg text-[10px] font-bold uppercase tracking-widest hover:bg-white/20 transition-all text-white">
                <Download className="w-3.5 h-3.5" />
                Download .md
              </button>
              <button onClick={handleCopy} className="flex items-center gap-2 px-4 py-2 bg-white/10 border border-white/10 rounded-lg text-[10px] font-bold uppercase tracking-widest hover:bg-white/20 transition-all text-white">
                {copied ? <Check className="w-3.5 h-3.5 text-brand-primary" /> : <Copy className="w-3.5 h-3.5" />}
                {copied ? 'Copied' : 'Copy MD'}
              </button>
              <button onClick={handleEmail} className="flex items-center gap-2 px-4 py-2 bg-white/10 border border-white/10 rounded-lg text-[10px] font-bold uppercase tracking-widest hover:bg-white/20 transition-all text-white">
                {sent ? <Check className="w-3.5 h-3.5 text-brand-primary" /> : <Mail className="w-3.5 h-3.5" />}
                {sent ? 'Sent' : 'Export via Email'}
              </button>
              <button onClick={() => setReport(null)} className="px-4 py-2 text-[10px] text-white/40 hover:text-white uppercase font-bold tracking-widest transition-colors">
                Regenerate
              </button>
            </div>
          )}
          
          {activeBuilds.length === 0 && !isGenerating && (
            <div className="mt-4 flex items-center gap-2 text-[10px] text-brand-alert uppercase font-bold tracking-widest">
              <AlertCircle className="w-3 h-3" />
              No active builds detected in current session.
            </div>
          )}
        </div>
      </div>

      <AnimatePresence>
        {report && (
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: 20 }}
            className="bg-white/5 border border-white/10 rounded-2xl overflow-hidden"
          >
            <div className="bg-white/5 px-6 py-3 border-b border-white/10 flex justify-between items-center">
              <span className="text-[10px] text-white/40 font-mono uppercase tracking-widest">Report Preview</span>
              <div className="flex gap-1.5">
                <div className="w-2 h-2 rounded-full bg-red-500/50" />
                <div className="w-2 h-2 rounded-full bg-yellow-500/50" />
                <div className="w-2 h-2 rounded-full bg-green-500/50" />
              </div>
            </div>
            <div className="p-8 prose prose-invert prose-xs max-w-none prose-headings:text-brand-primary prose-table:border prose-table:border-white/10 prose-th:bg-white/5 prose-th:p-2 prose-td:p-2">
              <ReactMarkdown>{report}</ReactMarkdown>
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
};
